baseURL = '/'
languageCode = 'en-us'
title="Users/ollie/website"
author="Ollie"

# THEME SPECIFIC
theme = 'risotto'
paginate=3
sectionPagesMenu = "main"
enableInlineShortcodes = true

[params]
  noindex = true

[params.theme]
  palette = "gruvbox-dark"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[params.about]
  title = "Ollie Lawrence"
  description = "A former computer science student who has a lot of free time."
  logo = "/cool-emoji.png"

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/otwl169"